-- ============================================================
-- seed.sql — Seed data for MasterShop
-- ============================================================

INSERT INTO public.products (title, description, price_vnd, slug, images, stock) VALUES
  ('{"vi": "Áo Thun Cotton Cơ Bản", "en": "Basic Cotton T-Shirt"}', '{"vi": "Áo thun cotton 100% thoáng mát, thấm hút mồ hôi tốt. Phù hợp mặc hàng ngày.", "en": "100% cotton t-shirt, breathable and sweat-absorbent. Perfect for daily wear."}', 150000, 'basic-cotton-t-shirt', ARRAY['https://placehold.co/600x800/png?text=T-Shirt'], 100),
  ('{"vi": "Quần Jeans Nam Phom Chuẩn", "en": "Men''s Regular Fit Jeans"}', '{"vi": "Quần jeans chất liệu denim bền bỉ, phom dáng chuẩn, dễ phối đồ.", "en": "Durable denim jeans, regular fit, easy to match with other clothes."}', 450000, 'mens-regular-fit-jeans', ARRAY['https://placehold.co/600x800/png?text=Jeans'], 50),
  ('{"vi": "Giày Thể Thao Chạy Bộ", "en": "Running Sneakers"}', '{"vi": "Giày chạy bộ siêu nhẹ, đế êm ái, hỗ trợ tối đa cho từng bước chạy.", "en": "Ultra-light running shoes with soft soles, providing maximum support for every step."}', 850000, 'running-sneakers', ARRAY['https://placehold.co/600x800/png?text=Sneakers'], 75),
  ('{"vi": "Balo Laptop Chống Nước", "en": "Waterproof Laptop Backpack"}', '{"vi": "Balo có ngăn chống sốc chuyên dụng cho laptop 15.6 inch, chất liệu vải chống nước.", "en": "Backpack with a dedicated shockproof compartment for 15.6-inch laptops, waterproof fabric."}', 650000, 'waterproof-laptop-backpack', ARRAY['https://placehold.co/600x800/png?text=Backpack'], 30),
  ('{"vi": "Đồng Hồ Thông Minh Bản Thể Thao", "en": "Smartwatch Sport Edition"}', '{"vi": "Đồng hồ thông minh theo dõi sức khỏe, nhịp tim, giấc ngủ và chế độ luyện tập.", "en": "Smartwatch for tracking health, heart rate, sleep, and workout modes."}', 1200000, 'smartwatch-sport-edition', ARRAY['https://placehold.co/600x800/png?text=Smartwatch'], 40),
  ('{"vi": "Tai Nghe Bluetooth Chống Ồn", "en": "Noise Cancelling Bluetooth Headphones"}', '{"vi": "Tai nghe không dây với công nghệ chống ồn chủ động (ANC), âm thanh chất lượng cao.", "en": "Wireless headphones with Active Noise Cancellation (ANC) technology, high-quality sound."}', 2100000, 'noise-cancelling-headphones', ARRAY['https://placehold.co/600x800/png?text=Headphones'], 25),
  ('{"vi": "Chuột Không Dây Tiện Dụng", "en": "Ergonomic Wireless Mouse"}', '{"vi": "Chuột không dây thiết kế công thái học, giúp giảm mỏi tay khi sử dụng lâu.", "en": "Ergonomic wireless mouse, reduces hand fatigue during prolonged use."}', 250000, 'ergonomic-wireless-mouse', ARRAY['https://placehold.co/600x800/png?text=Mouse'], 120),
  ('{"vi": "Bàn Phím Cơ Đèn LED", "en": "Mechanical Keyboard with LED"}', '{"vi": "Bàn phím cơ với switch chất lượng, tích hợp đèn LED RGB nhiều chế độ.", "en": "Mechanical keyboard with quality switches, integrated multi-mode RGB LED."}', 1500000, 'mechanical-keyboard-led', ARRAY['https://placehold.co/600x800/png?text=Keyboard'], 60),
  ('{"vi": "Kính Mát Thời Trang Nam Nữ", "en": "Unisex Fashion Sunglasses"}', '{"vi": "Kính mát thiết kế hiện đại, chống tia UV bảo vệ mắt hoàn hảo.", "en": "Sunglasses with modern design, UV protection for perfect eye care."}', 350000, 'unisex-fashion-sunglasses', ARRAY['https://placehold.co/600x800/png?text=Sunglasses'], 80),
  ('{"vi": "Bình Nước Giữ Nhiệt Inox", "en": "Stainless Steel Thermos Flask"}', '{"vi": "Bình giữ nhiệt chất liệu inox 304 an toàn, giữ nóng 12h và giữ lạnh 24h.", "en": "Thermos flask made of safe 304 stainless steel, keeps hot for 12h and cold for 24h."}', 200000, 'stainless-steel-thermos', ARRAY['https://placehold.co/600x800/png?text=Thermos'], 150);
